version: '2.1'
orbs:
  docker: circleci/docker@2.0.2
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: favish/php-7.3-fpm-xdebug
          update-description: true
          tag: $CIRCLE_TAG
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          context:
            - dockerhub